apiVersion: v1
kind: Service
metadata:
  name: juiceshop-chatbot-backend
  namespace: juiceshop-chatbot
  labels:
    app.kubernetes.io/name: juiceshop-chatbot-backend
    app.kubernetes.io/instance: juiceshop-chatbot
    app.kubernetes.io/part-of: juiceshop-chatbot
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: juiceshop-chatbot-backend
    app.kubernetes.io/instance: juiceshop-chatbot
    app.kubernetes.io/component: backend
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
  sessionAffinity: None
