{{- if .Values.ingress.enabled }}
{{- if .Values.backend.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "juiceshop-chatbot.fullname" . }}-backend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "juiceshop-chatbot.labels" . | nindent 4 }}
    app.kubernetes.io/component: ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: {{ .Values.ingress.backendRewriteTarget | quote }}
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: {{ .Values.ingress.backendPath | quote }}
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "juiceshop-chatbot.backend.fullname" . }}
                port:
                  number: {{ .Values.backend.service.port }}
{{- end }}
---
{{- if .Values.frontend.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "juiceshop-chatbot.fullname" . }}-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "juiceshop-chatbot.labels" . | nindent 4 }}
    app.kubernetes.io/component: ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-http-version: "1.1"
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "juiceshop-chatbot.frontend.fullname" . }}
                port:
                  number: {{ .Values.frontend.service.port }}
{{- end }}
{{- end }}
