# Local KIND overlay
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: juiceshop-chatbot

resources:
- ../../base
- pv.yaml

images:
- name: owasp-juiceshop-chatbot-backend
  newName: ghcr.io/amaninsa/backend
  newTag: 5e9f2b829287157883de6859cc012288c5207db2
- name: owasp-juiceshop-chatbot-chromadb
  newName: owasp-juiceshop-chatbot-chromadb
  newTag: local
- name: owasp-juiceshop-chatbot-frontend
  newName: ghcr.io/amaninsa/frontend
  newTag: 5e9f2b829287157883de6859cc012288c5207db2

replicas:
- count: 1
  name: juiceshop-chatbot-frontend
- count: 1
  name: juiceshop-chatbot-backend
- count: 1
  name: juiceshop-chatbot-chromadb

patches:
- path: patches/ingress-host.yaml
- path: patches/configmap-local.yaml
- path: patches/resources-local.yaml
