# Local KIND overlay
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: juiceshop-chatbot

resources:
  - ../../base
  - pv.yaml

images:
  - name: owasp-juiceshop-chatbot-chromadb
    newName: owasp-juiceshop-chatbot-chromadb
    newTag: local
  - name: owasp-juiceshop-chatbot-backend
    newName: owasp-juiceshop-chatbot-backend
    newTag: local
  - name: owasp-juiceshop-chatbot-frontend
    newName: owasp-juiceshop-chatbot-frontend
    newTag: local

replicas:
  - name: juiceshop-chatbot-frontend
    count: 1
  - name: juiceshop-chatbot-backend
    count: 1
  - name: juiceshop-chatbot-chromadb
    count: 1

patches:
  - path: patches/ingress-host.yaml
  - path: patches/configmap-local.yaml
  - path: patches/resources-local.yaml
