apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: juiceshop-chatbot-backend
  namespace: juiceshop-chatbot
spec:
  rules:
    - host: juiceshop-chatbot.dev.local
      http:
        paths:
          - path: /ai-assistant(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: juiceshop-chatbot-backend
                port:
                  number: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: juiceshop-chatbot-frontend
  namespace: juiceshop-chatbot
spec:
  rules:
    - host: juiceshop-chatbot.dev.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: juiceshop-chatbot-frontend
                port:
                  number: 3000
